#
# 
# Based on:
# https://github.com/openstack/heat-templates/blob/master/hot/F20/WordPress_2_Instances.yaml
# https://github.com/openstack/heat-templates/blob/master/hot/servers_in_new_neutron_net.yaml
#

heat_template_version: 2013-05-23

description: >
  An example Heat Orchestration Template (HOT).
  WordPress is web software you can use to create a beautiful website
  or blog. This template installs two instances: one running a
  WordPress deployment and the other using a local MySQL database to
  store the data.
parameters:

  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance
    default: test_key

  instance_type:
    type: string
    description: Instance type for web and DB servers
    default: m1.small
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
        description: instance_type must be a valid instance type

  image_id:
    type: string
    description: >
      Name or ID of the image to use for the WordPress server.
      Recommended values are fedora-20.i386 or fedora-20.x86_64;
      get them from http://cloud.fedoraproject.org/fedora-20.i386.qcow2
      or http://cloud.fedoraproject.org/fedora-20.x86_64.qcow2 .
    default: fedora-20.x86_64

  db_name:
    type: string
    description: WordPress database name
    default: wordpress
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters
  db_username:
    type: string
    description: The WordPress database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 16 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters
  db_password:
    type: string
    description: The WordPress database admin account password
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters

  db_root_password:
    type: string
    description: Root password for MySQL
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_root_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_root_password must contain only alphanumeric characters

  public_net:
    type: string
    description: ID or name of public network from which floating IP addresses will be allocated
    default: Public

  public_net_id:
    type: string
    description: >
      Neutron floatingip resource in icehouse does not support
      network name. This parameter should be removed for future versions.

  frontend_net_name:
    type: string
    description: Webservers are isolated in this network.
    default: wordpress

  frontend_net_cidr:
    type: string
    description: The IP prefixes of the subnets used by the application should be unique.
    default: 192.168.0.0/24

  database_net_name:
    type: string
    description: Database server(s) are isolated in this network.
    default: database

  database_net_cidr:
    type: string
    description: The IP prefixes of the subnets used by the application should be unique.
    default: 192.168.1.0/24

resources:
  FrontendNet:
    type: OS::Neutron::Net
    properties:
      name: { get_param: frontend_net_name }

  FrontendSubnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: FrontendNet }
      cidr: { get_param: frontend_net_cidr }

  DatabaseNet:
    type: OS::Neutron::Net
    properties:
      name: { get_param: database_net_name }

  DatabaseSubnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: DatabaseNet }
      cidr: { get_param: database_net_cidr }

  Router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }
 
  FrontendRouterInterface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: Router }
      subnet_id: { get_resource: FrontendSubnet }

  DatabaseRouterInterface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: Router }
      subnet_id: { get_resource: DatabaseSubnet }

  DatabaseServer:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            yum -y install mariadb mariadb-server
            touch /var/log/mariadb/mariadb.log
            chown mysql.mysql /var/log/mariadb/mariadb.log
            systemctl start mariadb.service

            # Setup MySQL root password and create a user
            mysqladmin -u root password db_rootpassword
            cat << EOF | mysql -u root --password=db_rootpassword
            CREATE DATABASE db_name;
            GRANT ALL PRIVILEGES ON db_name.* TO "db_user"@"%"
            IDENTIFIED BY "db_password";
            FLUSH PRIVILEGES;
            EXIT
            EOF
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
      networks:
        - port: { get_resource: DatabasePort }

  DatabasePort:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: DatabaseNet }

  WebServer:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            yum -y install httpd wordpress

            sed -i "/Deny from All/d" /etc/httpd/conf.d/wordpress.conf
            sed -i "s/Require local/Require all granted/" /etc/httpd/conf.d/wordpress.conf
            sed -i s/database_name_here/db_name/ /etc/wordpress/wp-config.php
            sed -i s/username_here/db_user/      /etc/wordpress/wp-config.php
            sed -i s/password_here/db_password/  /etc/wordpress/wp-config.php
            sed -i s/localhost/db_ipaddr/        /etc/wordpress/wp-config.php
            setenforce 0 # Otherwise net traffic with DB is disabled
            systemctl start httpd.service
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
            db_ipaddr: { get_attr: [DatabaseServer, first_address ] }
      networks:
        - port: { get_resource: FrontendPort }

  FrontendPort:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: FrontendNet }

  Member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: { get_resource: LoadbalancerPool }
      address: { get_attr: [WebServer, first_address]}
      protocol_port: 80

  LoadbalancerPool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      subnet_id: { get_resource: FrontendSubnet }
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 80

  FloatingIp:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { "Fn::Select" : [ "port_id", { get_attr: [ LoadbalancerPool , vip ] } ] }

outputs:
  WebsiteURL:
    description: URL for Wordpress wiki
    value:
      str_replace:
        template: http://host/wordpress
        params:
          host: { get_attr: [FloatingIp, floating_ip_address] }

